/* Includes all of toc's files */
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <stdint.h>
#include <stdbool.h>
#include "util/err.c"
#include "util/arr.c"
#include "util/blockarr.c"
#include "util/str.c"
#include "identifiers.c"
#include "tokenizer.c"
#include "parse.c"
#include "types.c"
#include "base_cgen.c"
#include "decls_cgen.c"
#include "cgen.c"
